### ISSUE TITLE
[Update] SQL statement to find current chunk interval

### ISSUE THREAD

**Issue by mfreed** [timescale/docs.timescale.com-content#406]
Eventually, an information view should specify the current chunk interval.  Until then, we should let folks know how to do this in the docs:

> SELECT h.table_name, c.interval_length   FROM _timescaledb_catalog.dimension c JOIN _timescaledb_catalog.hypertable h ON h.id = c.hypertable_id;

Should likely add this to hypertable section on specifying dimension, as well as API reference.

**Comment by tylerfontaine** [comment]
@mfreed I've added a PR for docs to add this. I also have the view definition ready to update the `timescaledb_information.hypertable` to show this (as well as interval type, since there are both time and integers) for a PR, but I'll ask around for help on fixing tests and things before submitting that.

**Comment by gayyappan** [comment]
For 2.0, this information is available via timescaledb_information.dimensions view.

**Comment by solugebefola** [comment]
Fixed by #454
